---
# tasks file for podman

- name: add podman ppa
  apt_repository:
    repo: ppa:projectatomic/ppa
    state: absent
  become: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version}}/Release.key
    state: present
  become: yes

- apt_repository:
    repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version}}/ /
    state: present
  become: yes

- name: Update repositories cache and install podman packages
  apt:
    name:
      - podman
      - buildah
      - skopeo
      - slirp4netns
      - python3-pip
    update_cache: yes
    state: latest
  become: yes


- name: Create a new volume in pool zroot.
  zfs:
    name: "{{ containers_zfs_fs }}"
    state: present
  when: containers_fs == "zfs"
  become: yes


- debug: msg="{{ ansible_distribution_release }}"

- name: newer fuse-overlayfs than ubuntu includes when using focal
  block:
    - name: clone fuse-overlayfs
      git:
        repo: https://github.com/containers/fuse-overlayfs/
        dest:  /opt/fuse-overlayfs/
        version: v1.0.0
    - name: static build fuse-overlayfs via buildah
      command: buildah bud -v /opt/fuse-overlayfs/:/build/fuse-overlayfs -t fuse-overlayfs -f ./Dockerfile.static.ubuntu .
      args:
        chdir: /opt/fuse-overlayfs/
        creates: /opt/fuse-overlayfs/fuse-overlayfs
    - name: copy fuse-overlayfs to /usr/local/bin/fuse-overlayfs
      copy:
        remote_src: yes
        src: /opt/fuse-overlayfs/fuse-overlayfs
        dest: /usr/local/bin/fuse-overlayfs
    - name: use correct path for fuse-overlayfs
      set_fact:
        fuseoverlayfs_path: /usr/local/bin/fuse-overlayfs
  when: ansible_distribution_release in ["bionic", "focal"]


- name: install fuse-overlayfs from apt
  apt:
    name:
      - fuse-overlayfs
    update_cache: yes
    state: latest
  become: yes
  when: ansible_distribution_release in ["bionic", "focal"]






- name: configure storage.conf
  template:
    src: "storage.conf.{{ containers_fs }}.j2"
    dest: /etc/containers/storage.conf
    backup: yes
  become: yes

- name: install podman-compose
  pip:
    name: https://github.com/containers/podman-compose/archive/devel.tar.gz
    executable: pip3
    state: latest
  become: yes



